### ISSUE TITLE
Enable monitoring of multiple Stream keys

### ISSUE THREAD

**Issue by chrnola** [chrnola/redis-streams-exporter#2]
Currently we only support monitoring single Streams. Would be great to have a single instance of the app monitor multiple streams concurrently in the same database.

**Comment by danielrosa-zh** [comment]
First of all, thanks for create this project. I started to use it and now I have to create one exporter per stream. Monitor multiple streams would be awesome. Thanks.

**Comment by chrnola** [comment]
@danielrosa-zh multi-stream support has been added in v0.6 👍

**Comment by chrnola** [comment]
For what it's worth, https://github.com/oliver006/redis_exporter now has streams support (plus groups). To be perfectly honest I'd recommend using that over this project since it's more actively maintained.

**Comment by danielrosa-zh** [comment]
@chrnola , great!
good to know that this from oliver support stream. Thanks a lot!
